[package]
name = "sarnath"
version = "0.1.0"
authors = ["solidiquis <benjamin.van.nguyen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
libc = "0.2.98"
rand = "0.8.4"
